import os

home = os.path.expanduser("~")
path = os.path.join(home, "legal-tracker", "src", "server.js")

lines = []
lines.append("import express from 'express';")
lines.append("import { ACCOUNTS } from '../config/accounts.js';")
lines.append("import { getAllResearch, getLatestDigest, db } from './db.js';")
lines.append("import { logger } from './logger.js';")
lines.append("")
lines.append("const app = express();")
lines.append("app.use(express.json());")
lines.append("")
lines.append("app.get('/api/accounts', async (req, res) => {")
lines.append("  const allResearch = await getAllResearch();")
lines.append("  const data = ACCOUNTS.map(a => ({")
lines.append("    ...a,")
lines.append("    hasData: !!allResearch[a.id],")
lines.append("    lastUpdated: db.data.lastUpdated?.[a.id] || null,")
lines.append("    contactCount: allResearch[a.id]?.contacts?.length || 0,")
lines.append("    activeIssues: [")
lines.append("      ...(allResearch[a.id]?.litigation || []).filter(l => !['Resolved','Settled','Dismissed'].includes(l.status)),")
lines.append("      ...(allResearch[a.id]?.regulatory || []).filter(r => !['Resolved','Closed'].includes(r.status)),")
lines.append("    ].length,")
lines.append("    intelSummary: allResearch[a.id]?.intel_summary || null,")
lines.append("  }));")
lines.append("  res.json(data);")
lines.append("});")
lines.append("")
lines.append("app.get('/api/accounts/:id', async (req, res) => {")
lines.append("  const account = ACCOUNTS.find(a => a.id === req.params.id);")
lines.append("  if (!account) return res.status(404).json({ error: 'Account not found' });")
lines.append("  const allResearch = await getAllResearch();")
lines.append("  res.json({ ...account, lastUpdated: db.data.lastUpdated?.[account.id] || null, research: allResearch[account.id] || null });")
lines.append("});")
lines.append("")
lines.append("app.get('/api/digest', async (req, res) => {")
lines.append("  const digest = await getLatestDigest();")
lines.append("  res.json(digest || { message: 'No digest generated yet' });")
lines.append("});")
lines.append("")
lines.append("app.get('/api/status', async (req, res) => {")
lines.append("  await db.read();")
lines.append("  const allResearch = await getAllResearch();")
lines.append("  const researched = Object.keys(allResearch).length;")
lines.append("  res.json({ status: 'ok', accounts: ACCOUNTS.length, researched, pending: ACCOUNTS.length - researched, recentRuns: (db.data.runs || []).slice(0, 5) });")
lines.append("});")
lines.append("")
lines.append("app.get('/', (req, res) => res.send(getDash()));")
lines.append("")
lines.append("export function startServer() {")
lines.append("  const port = process.env.PORT || 3000;")
lines.append("  app.listen(port, () => logger.info('Dashboard running at http://localhost:' + port));")
lines.append("  return app;")
lines.append("}")
lines.append("")
lines.append("function getDash() {")
lines.append("  return `<!DOCTYPE html>")
lines.append("<html lang='en'>")
lines.append("<head>")
lines.append("<meta charset='utf-8'>")
lines.append("<meta name='viewport' content='width=device-width,initial-scale=1'>")
lines.append("<title>Legal Account Tracker</title>")
lines.append("<link href='https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600&family=DM+Mono:wght@400;500&display=swap' rel='stylesheet'>")
lines.append("<style>")
lines.append("*{box-sizing:border-box;margin:0;padding:0}")
lines.append(":root{--navy:#0F2240;--blue:#1E56A0;--bl:#EBF2FC;--teal:#0A7C6E;--tl:#E6F5F2;--amber:#B45309;--al:#FEF3C7;--red:#991B1B;--rl:#FEE2E2;--green:#166534;--gl:#DCFCE7;--g0:#F9FAFB;--g1:#F3F4F6;--g2:#E5E7EB;--g4:#9CA3AF;--g5:#6B7280;--g6:#4B5563;--g7:#374151;--g9:#111827;--f:'DM Sans',sans-serif;--m:'DM Mono',monospace;--r:10px;--rl2:14px}")
lines.append("body{font-family:var(--f);font-size:14px;color:var(--g9);background:var(--g0);height:100vh;overflow:hidden;display:flex;flex-direction:column}")
lines.append(".tb{height:52px;background:var(--navy);display:flex;align-items:center;padding:0 20px;gap:12px;flex-shrink:0}")
lines.append(".tb-t{font-size:15px;font-weight:600;color:#fff}")
lines.append(".tb-s{font-size:12px;color:rgba(255,255,255,.4)}")
lines.append(".tb-r{margin-left:auto;display:flex;align-items:center;gap:10px}")
lines.append(".ts{font-size:12px;color:rgba(255,255,255,.55);display:flex;align-items:center;gap:5px}")
lines.append(".ts strong{color:rgba(255,255,255,.9);font-weight:500}")
lines.append(".td{width:1px;height:16px;background:rgba(255,255,255,.12)}")
lines.append(".dot{width:7px;height:7px;border-radius:50%;background:#34D399}")
lines.append(".lay{display:flex;flex:1;overflow:hidden}")
lines.append(".sb{width:240px;background:#fff;border-right:1px solid var(--g2);display:flex;flex-direction:column;overflow:hidden}")
lines.append(".sb-s{padding:10px}")
lines.append(".sb-i{display:flex;align-items:center;gap:7px;background:var(--g0);border:1px solid var(--g2);border-radius:var(--r);padding:6px 10px}")
lines.append(".sb-i input{border:none;background:none;outline:none;font-size:12px;color:var(--g7);font-family:var(--f);width:100%}")
lines.append(".sb-i input::placeholder{color:var(--g4)}")
lines.append(".al{flex:1;overflow-y:auto;padding:4px 8px 8px}")
lines.append(".ai{display:flex;align-items:center;gap:8px;padding:7px 9px;border-radius:var(--r);cursor:pointer;border:1px solid transparent;margin-bottom:1px;transition:all .12s}")
lines.append(".ai:hover{background:var(--g0);border-color:var(--g2)}")
lines.append(".ai.active{background:var(--bl);border-color:#BFCFE8}")
lines.append(".aav{width:27px;height:27px;border-radius:6px;display:flex;align-items:center;justify-content:center;font-size:10px;font-weight:600;flex-shrink:0}")
lines.append(".an{font-size:12px;font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--g7)}")
lines.append(".ai.active .an{color:var(--blue)}")
lines.append(".as{font-size:10px;color:var(--g4);margin-top:1px}")
lines.append(".mn{flex:1;display:flex;flex-direction:column;overflow:hidden;min-width:0}")
lines.append(".na{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;color:var(--g4)}")
lines.append(".ah{padding:14px 20px 0;border-bottom:1px solid var(--g2);flex-shrink:0}")
lines.append(".ah-t{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:12px}")
lines.append(".ah-l{display:flex;align-items:center;gap:11px}")
lines.append(".hav{width:38px;height:38px;border-radius:9px;display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:600;flex-shrink:0}")
lines.append(".hn{font-size:17px;font-weight:600;color:var(--g9);letter-spacing:-.02em}")
lines.append(".hm{font-size:11px;color:var(--g5);margin-top:2px;display:flex;align-items:center;gap:6px;flex-wrap:wrap}")
lines.append(".bdg{display:inline-flex;align-items:center;font-size:10px;font-weight:500;padding:2px 7px;border-radius:20px}")
lines.append(".bg{background:var(--gl);color:var(--green)}")
lines.append(".ba{background:var(--al);color:var(--amber)}")
lines.append(".br{background:var(--rl);color:var(--red)}")
lines.append(".bb{background:var(--bl);color:var(--blue)}")
lines.append(".tabs{display:flex;overflow-x:auto;scrollbar-width:none;margin-top:2px}")
lines.append(".tabs::-webkit-scrollbar{display:none}")
lines.append(".tab{padding:8px 13px;font-size:12px;font-weight:500;cursor:pointer;border-bottom:2px solid transparent;color:var(--g5);white-space:nowrap;transition:all .12s;display:flex;align-items:center;gap:4px}")
lines.append(".tab:hover{color:var(--g7)}")
lines.append(".tab.active{color:var(--blue);border-bottom-color:var(--blue)}")
lines.append(".tc{font-size:10px;padding:1px 5px;border-radius:10px;background:var(--g1);color:var(--g5)}")
lines.append(".tab.active .tc{background:var(--bl);color:var(--blue)}")
lines.append(".ct{flex:1;overflow-y:auto;padding:18px}")
lines.append(".sl{font-size:11px;font-weight:600;color:var(--g4);text-transform:uppercase;letter-spacing:.06em;margin-bottom:9px;display:flex;align-items:center;gap:6px}")
lines.append(".sl::after{content:'';flex:1;height:1px;background:var(--g1)}")
lines.append(".card{background:#fff;border:1px solid var(--g2);border-radius:var(--rl2);padding:13px;margin-bottom:9px}")
lines.append(".cg{display:grid;grid-template-columns:repeat(auto-fill,minmax(195px,1fr));gap:9px;margin-bottom:12px}")
lines.append(".cc{background:#fff;border:1px solid var(--g2);border-radius:var(--rl2);padding:12px;transition:all .12s}")
lines.append(".cc:hover{box-shadow:0 4px 6px rgba(0,0,0,.07);transform:translateY(-1px)}")
lines.append(".cc-t{display:flex;align-items:center;gap:8px;margin-bottom:7px}")
lines.append(".cav{width:32px;height:32px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:600;flex-shrink:0}")
lines.append(".cn{font-size:12px;font-weight:600;color:var(--g9);line-height:1.3}")
lines.append(".ct2{font-size:10px;color:var(--g5)}")
lines.append(".cd{font-size:10px;color:var(--g5);display:flex;align-items:center;gap:3px;margin-top:3px}")
lines.append(".cd a{color:var(--blue);text-decoration:none}")
lines.append(".tag{display:inline-block;font-size:10px;font-weight:500;padding:2px 7px;border-radius:20px;margin-bottom:5px}")
lines.append(".t-clo{background:#F0EEFE;color:#5B45C7}")
lines.append(".t-gc{background:var(--bl);color:var(--blue)}")
lines.append(".t-lit{background:var(--al);color:var(--amber)}")
lines.append(".t-ops{background:var(--tl);color:var(--teal)}")
lines.append(".t-def{background:var(--g1);color:var(--g6)}")
lines.append(".conf-h{font-size:10px;color:var(--green);font-weight:500}")
lines.append(".conf-m{font-size:10px;color:var(--amber);font-weight:500}")
lines.append(".conf-l{font-size:10px;color:var(--red);font-weight:500}")
lines.append(".pr{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:14px}")
lines.append(".pill{font-size:12px;padding:4px 10px;border-radius:20px;border:1px solid var(--g2);color:var(--g6);background:#fff}")
lines.append(".p-bl{background:var(--bl);color:var(--blue);border-color:#BFCFE8}")
lines.append(".p-tl{background:var(--tl);color:var(--teal);border-color:#A7D7D0}")
lines.append(".p-pu{background:#F0EEFE;color:#5B45C7;border-color:#C4BAF5}")
lines.append(".ir{background:#fff;border:1px solid var(--g2);border-radius:var(--rl2);padding:12px;margin-bottom:8px}")
lines.append(".ir-tp{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:3px;gap:8px}")
lines.append(".ir-ti{font-size:13px;font-weight:600;color:var(--g9)}")
lines.append(".ir-pe{font-size:10px;color:var(--g4);margin-bottom:4px}")
lines.append(".ir-su{font-size:12px;color:var(--g6);line-height:1.6;margin-bottom:5px}")
lines.append(".ir-co{font-size:11px;color:var(--g5)}")
lines.append(".new-tag{font-size:10px;background:#FEE2E2;color:#991B1B;padding:1px 6px;border-radius:10px;font-weight:600;margin-left:6px}")
lines.append(".intel{background:linear-gradient(135deg,#FFF8E7,#FFFBF0);border:1px solid #FDE68A;border-radius:var(--rl2);padding:13px;margin-bottom:15px}")
lines.append(".il{font-size:10px;font-weight:700;color:var(--amber);text-transform:uppercase;letter-spacing:.08em;margin-bottom:4px}")
lines.append(".it{font-size:13px;color:var(--g7);line-height:1.65}")
lines.append(".trig{background:var(--g0);border:1px solid var(--g2);border-radius:var(--r);padding:9px 11px;margin-bottom:6px;font-size:12px;color:var(--g6);line-height:1.5}")
lines.append(".emp{padding:32px 16px;text-align:center;color:var(--g4)}")
lines.append("code{font-family:var(--m);background:var(--g1);padding:2px 6px;border-radius:4px;font-size:11px}")
lines.append("@keyframes fi{from{opacity:0;transform:translateY(3px)}to{opacity:1;transform:translateY(0)}}")
lines.append(".ct>*{animation:fi .15s ease}")
lines.append("</style>")
lines.append("</head>")
lines.append("<body>")
lines.append("<div class='tb'>")
lines.append("  <span style='font-size:18px'>&#9878;</span>")
lines.append("  <span class='tb-t'>Legal Account Tracker</span>")
lines.append("  <span class='tb-s'>Intelligence Dashboard</span>")
lines.append("  <div class='tb-r'>")
lines.append("    <div class='ts'><strong id='sr'>-</strong> researched</div>")
lines.append("    <div class='td'></div>")
lines.append("    <div class='ts'><strong id='si'>-</strong> active issues</div>")
lines.append("    <div class='td'></div>")
lines.append("    <div class='ts'><div class='dot'></div> Live</div>")
lines.append("  </div>")
lines.append("</div>")
lines.append("<div class='lay'>")
lines.append("  <div class='sb'>")
lines.append("    <div class='sb-s'><div class='sb-i'>")
lines.append("      <svg width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.5'><circle cx='11' cy='11' r='8'/><path d='m21 21-4.35-4.35'/></svg>")
lines.append("      <input id='srch' placeholder='Search accounts...' oninput='filt()'>")
lines.append("    </div></div>")
lines.append("    <div class='al' id='list'></div>")
lines.append("  </div>")
lines.append("  <div class='mn' id='mn'>")
lines.append("    <div class='na' id='na'>")
lines.append("      <svg width='44' height='44' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.2' opacity='.2'><path d='M3 21h18M9 8h1M9 12h1M9 16h1M14 8h1M14 12h1M14 16h1M5 21V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16'/></svg>")
lines.append("      <p>Select an account to view intelligence</p>")
lines.append("    </div>")
lines.append("    <div id='vw' style='display:none;flex-direction:column;height:100%;overflow:hidden'>")
lines.append("      <div class='ah'>")
lines.append("        <div class='ah-t'><div class='ah-l'>")
lines.append("          <div class='hav' id='hav'></div>")
lines.append("          <div><div class='hn' id='hn'></div><div class='hm' id='hm'></div></div>")
lines.append("        </div></div>")
lines.append("        <div class='tabs' id='tabs'></div>")
lines.append("      </div>")
lines.append("      <div class='ct' id='cnt'></div>")
lines.append("    </div>")
lines.append("  </div>")
lines.append("</div>")
lines.append("<script>")
lines.append("const COLS=[['#EBF2FC','#1E56A0'],['#E6F5F2','#0A7C6E'],['#F0EEFE','#5B45C7'],['#FEF3C7','#B45309'],['#FEE2E2','#991B1B'],['#DCFCE7','#166534'],['#FFF0F3','#9D174D']];")
lines.append("let all=[],aid=null,atab='contacts';")
lines.append("const ini=n=>n.split(/[\\\\s\\\\/\\\\-]+/).map(w=>w[0]).join('').slice(0,2).toUpperCase();")
lines.append("const col=i=>COLS[i%COLS.length];")
lines.append("const sbdg=s=>'<span class=\\'bdg '+({'Pending':'ba','Ongoing':'ba','Under investigation':'ba','Resolved':'bg','Settled':'bg','Dismissed':'bg','Closed':'bg'}[s]||'bb')+'\\'>' +s+'</span>';")
lines.append("const itl=t=>'<div class=\\'intel\\'><div class=\\'il\\'>Sales Intel</div><div class=\\'it\\'>'+t+'</div></div>';")
lines.append("const emp=(m,c)=>'<div class=\\'emp\\'><p>'+m+'</p>'+(c?'<p style=\\'font-size:11px;margin-top:4px\\'>Run: <code>'+c+'</code></p>':'')+'</div>';")
lines.append("const tcls=t=>{const x=(t||'').toLowerCase().replace(/[^a-z]/g,'');return{clo:'t-clo',gc:'t-gc',litigation:'t-lit',litigator:'t-lit',headoflitigation:'t-lit',headoflegaloperations:'t-ops',legalops:'t-ops'}[x]||'t-def';};")
lines.append("const ccls=c=>c==='High'?'conf-h':c==='Medium'?'conf-m':'conf-l';")
lines.append("async function init(){")
lines.append("  const[ac,st]=await Promise.all([fetch('/api/accounts').then(r=>r.json()),fetch('/api/status').then(r=>r.json())]);")
lines.append("  all=ac;")
lines.append("  document.getElementById('sr').textContent=st.researched+'/'+st.accounts;")
lines.append("  document.getElementById('si').textContent=ac.reduce((s,a)=>s+a.activeIssues,0);")
lines.append("  rlist();")
lines.append("  const f=ac.find(a=>a.hasData)||ac[0];")
lines.append("  if(f)sel(f.id);")
lines.append("}")
lines.append("function filt(){rlist(document.getElementById('srch').value.toLowerCase());}")
lines.append("function rlist(q=''){")
lines.append("  const f=all.filter(a=>!q||a.name.toLowerCase().includes(q)||a.industry.toLowerCase().includes(q));")
lines.append("  const el=document.getElementById('list');")
lines.append("  if(!f.length){el.innerHTML='<div style=\\'padding:14px;text-align:center;color:#9CA3AF;font-size:12px\\'>No matches</div>';return;}")
lines.append("  el.innerHTML=f.map((a,i)=>{const[bg,tx]=col(i);return '<div class=\\'ai'+(a.id===aid?' active':'')+'\\''+' onclick=\\'sel(\\''+a.id+'\\')\\'>'+  '<div class=\\'aav\\' style=\\'background:'+bg+';color:'+tx+'\\'>'+ini(a.name)+'</div>'+  '<div style=\\'min-width:0\\'><div class=\\'an\\'>'+a.name+'</div>'+  '<div class=\\'as\\'>'+(a.activeIssues>0?'! '+a.activeIssues+' issue'+(a.activeIssues>1?'s':''):a.hasData?a.contactCount+' contacts':'needs research')+'</div></div></div>';}).join('');")
lines.append("}")
lines.append("async function sel(id){aid=id;rlist();const a=await fetch('/api/accounts/'+id).then(r=>r.json());show(a);}")
lines.append("function show(a){")
lines.append("  document.getElementById('na').style.display='none';")
lines.append("  document.getElementById('vw').style.display='flex';")
lines.append("  const i=all.findIndex(x=>x.id===a.id);const[bg,tx]=col(i);")
lines.append("  const av=document.getElementById('hav');av.style.background=bg;av.style.color=tx;av.textContent=ini(a.name);")
lines.append("  document.getElementById('hn').textContent=a.name;")
lines.append("  const upd=a.lastUpdated?new Date(a.lastUpdated).toLocaleDateString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Never';")
lines.append("  const ai=[...(a.research?.litigation||[]).filter(l=>!['Resolved','Settled','Dismissed'].includes(l.status)),...(a.research?.regulatory||[]).filter(r=>!['Resolved','Closed'].includes(r.status))].length;")
lines.append("  document.getElementById('hm').innerHTML=a.industry+'<span style=\\'color:#D1D5DB\\'> · </span>'+a.location+'<span style=\\'color:#D1D5DB\\'> · </span>'+(a.research?'<span class=\\'bdg bg\\'>Updated '+upd+'</span>':'<span class=\\'bdg ba\\'>Needs research</span>')+(ai>0?'<span style=\\'color:#D1D5DB\\'> · </span><span class=\\'bdg br\\'>'+ai+' active issue'+(ai>1?'s':'')+'</span>':'');")
lines.append("  const r=a.research||{};")
lines.append("  const tabs=[{id:'contacts',l:'Contacts',n:(r.contacts||[]).length},{id:'tech',l:'Technology',n:(r.tech||[]).length},{id:'counsel',l:'Counsel',n:(r.counsel||[]).length},{id:'alsp',l:'ALSPs',n:(r.alsp||[]).length+(r.flex||[]).length},{id:'litigation',l:'Litigation',n:(r.litigation||[]).length},{id:'regulatory',l:'Regulatory',n:(r.regulatory||[]).length},{id:'financial',l:'Financial Intel',n:null},{id:'triggers',l:'Sales Triggers',n:(r.sales_triggers||[]).length},{id:'outreach',l:'Outreach',n:null}];")
lines.append("  document.getElementById('tabs').innerHTML=tabs.map(t=>'<div class=\\'tab'+(t.id===atab?' active':'')+'\\''+' onclick=\\'stab(\\''+t.id+'\\',this)\\'>'+t.l+(t.n!==null?'<span class=\\'tc\\'>'+t.n+'</span>':'')+'</div>').join('');")
lines.append("  rtab(atab,a);")
lines.append("}")
lines.append("function stab(t,el){atab=t;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));if(el)el.classList.add('active');fetch('/api/accounts/'+aid).then(r=>r.json()).then(a=>rtab(t,a));}")
lines.append("function rtab(tab,a){")
lines.append("  const c=document.getElementById('cnt');const r=a.research;")
lines.append("  if(!r){c.innerHTML=emp('No research data yet for '+a.name,'npm run research:account \"'+a.name+'\"');return;}")
lines.append("  const i=all.findIndex(x=>x.id===a.id);const[bg,tx]=col(i);")
lines.append("  if(tab==='contacts'){")
lines.append("    if(!r.contacts?.length){c.innerHTML=emp('No contacts found');return;}")
lines.append("    c.innerHTML=(r.intel_summary?itl(r.intel_summary):'')+")
lines.append("      '<div class=\\'sl\\'>Key legal contacts ('+r.contacts.length+')</div>'+")
lines.append("      '<div class=\\'cg\\'>'+r.contacts.map(ct=>'<div class=\\'cc\\'><div class=\\'cc-t\\'><div class=\\'cav\\' style=\\'background:'+bg+';color:'+tx+'\\'>'+ini(ct.name)+'</div><div><div class=\\'cn\\'>'+ct.name+'</div><div class=\\'ct2\\'>'+ct.title+'</div></div></div><span class=\\'tag '+tcls(ct.tag)+'\\'>'+ct.tag+'</span>'+(ct.confidence?'<span class=\\''+ccls(ct.confidence)+'\\'>'+ct.confidence+' confidence</span>':'')+' '+(ct.email?'<div class=\\'cd\\'>@ '+ct.email+'</div>':'')+(ct.linkedin?'<div class=\\'cd\\'><a href=\\'https://'+ct.linkedin+'\\' target=\\'_blank\\'>LinkedIn</a></div>':'')+(ct.notes?'<div class=\\'cd\\' style=\\'font-style:italic;color:#9CA3AF\\'>'+ct.notes+'</div>':'')+(ct.confidence_reason?'<div class=\\'cd\\' style=\\'color:#9CA3AF\\'>'+ct.confidence_reason+'</div>':'')+'</div>').join('')+'</div>';")
lines.append("  }else if(tab==='tech'){")
lines.append("    c.innerHTML=(r.intel_summary?itl(r.intel_summary):'')+")
lines.append("      '<div class=\\'sl\\'>Legal technology stack</div>'+")
lines.append("      '<div class=\\'pr\\'>'+(r.tech||[]).map(t=>'<span class=\\'pill p-bl\\'>'+t+'</span>').join('')+'</div>';")
lines.append("  }else if(tab==='counsel'){")
lines.append("    if(!r.counsel?.length){c.innerHTML=emp('No outside counsel data');return;}")
lines.append("    c.innerHTML='<div class=\\'sl\\'>Primary outside counsel</div>'+(r.counsel||[]).map(f=>'<div class=\\'card\\' style=\\'font-size:13px\\'>'+f+'</div>').join('');")
lines.append("  }else if(tab==='alsp'){")
lines.append("    const ha=r.alsp?.length,hf=r.flex?.length;")
lines.append("    if(!ha&&!hf){c.innerHTML=emp('No ALSP or flex talent data');return;}")
lines.append("    c.innerHTML=(ha?'<div class=\\'sl\\'>ALSP relationships</div><div class=\\'pr\\'>'+r.alsp.map(x=>'<span class=\\'pill p-tl\\'>'+x+'</span>').join('')+'</div>':'')+")
lines.append("      (hf?'<div class=\\'sl\\'>Flex talent</div><div class=\\'pr\\'>'+r.flex.map(x=>'<span class=\\'pill p-pu\\'>'+x+'</span>').join('')+'</div>':'');")
lines.append("  }else if(tab==='litigation'){")
lines.append("    if(!r.litigation?.length){c.innerHTML=emp('No litigation data');return;}")
lines.append("    c.innerHTML='<div class=\\'sl\\'>Litigation ('+r.litigation.length+')</div>'+(r.litigation||[]).map(l=>'<div class=\\'ir\\'><div class=\\'ir-tp\\'><span class=\\'ir-ti\\'>'+l.type+(l.is_new?'<span class=\\'new-tag\\'>NEW</span>':'')+'</span>'+sbdg(l.status)+'</div><div class=\\'ir-pe\\'>'+l.period+'</div><div class=\\'ir-su\\'>'+l.summary+'</div><div class=\\'ir-co\\'>Outside counsel: <strong>'+(l.counsel||'Unknown')+'</strong></div></div>').join('');")
lines.append("  }else if(tab==='regulatory'){")
lines.append("    if(!r.regulatory?.length){c.innerHTML=emp('No regulatory data');return;}")
lines.append("    c.innerHTML='<div class=\\'sl\\'>Regulatory issues ('+r.regulatory.length+')</div>'+(r.regulatory||[]).map(x=>'<div class=\\'ir\\'><div class=\\'ir-tp\\'><span class=\\'ir-ti\\'>'+x.type+(x.is_new?'<span class=\\'new-tag\\'>NEW</span>':'')+'</span>'+sbdg(x.status)+'</div><div class=\\'ir-pe\\'>'+x.period+'</div><div class=\\'ir-su\\'>'+x.summary+'</div><div class=\\'ir-co\\'>Outside counsel: <strong>'+(x.counsel||'Unknown')+'</strong></div></div>').join('');")
lines.append("  }else if(tab==='financial'){")
lines.append("    const fi=r.financial_intel;")
lines.append("    if(!fi){c.innerHTML=emp('No financial intel yet','npm run research:account \"'+a.name+'\"');return;}")
lines.append("    c.innerHTML='<div class=\\'sl\\'>Financial and strategic intelligence</div>'+")
lines.append("      (fi.latest_filing?'<div class=\\'card\\'><div style=\\'font-size:11px;font-weight:600;color:#9CA3AF;text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px\\'>Latest filing</div><div style=\\'font-size:13px\\'>'+fi.latest_filing+'</div></div>':'')+")
lines.append("      (fi.cost_initiatives?'<div class=\\'card\\' style=\\'border-left:3px solid #B45309\\'><div style=\\'font-size:11px;font-weight:600;color:#B45309;text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px\\'>Cost initiatives</div><div style=\\'font-size:13px\\'>'+fi.cost_initiatives+'</div></div>':'')+")
lines.append("      (fi.earnings_signals?'<div class=\\'card\\'><div style=\\'font-size:11px;font-weight:600;color:#9CA3AF;text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px\\'>Earnings signals</div><div style=\\'font-size:13px\\'>'+fi.earnings_signals+'</div></div>':'')+")
lines.append("      (fi.legal_risk_factors?'<div class=\\'card\\'><div style=\\'font-size:11px;font-weight:600;color:#9CA3AF;text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px\\'>Legal risk factors (10-K)</div><div style=\\'font-size:13px\\'>'+fi.legal_risk_factors+'</div></div>':'')+")
lines.append("      (fi.ma_activity?'<div class=\\'card\\' style=\\'border-left:3px solid #1E56A0\\'><div style=\\'font-size:11px;font-weight:600;color:#1E56A0;text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px\\'>M&A activity</div><div style=\\'font-size:13px\\'>'+fi.ma_activity+'</div></div>':'');")
lines.append("  }else if(tab==='triggers'){")
lines.append("    const tr=r.sales_triggers||[];")
lines.append("    const pc=r.personnel_changes||[];")
lines.append("    if(!tr.length&&!pc.length){c.innerHTML=emp('No sales triggers yet','npm run research:account \"'+a.name+'\"');return;}")
lines.append("    c.innerHTML=")
lines.append("      (tr.length?'<div class=\\'sl\\'>Sales triggers ('+tr.length+')</div>'+tr.map(t=>'<div class=\\'trig\\'>'+t+'</div>').join(''):'')+")
lines.append("      (pc.length?'<div class=\\'sl\\' style=\\'margin-top:12px\\'>Personnel changes</div>'+pc.map(p=>'<div class=\\'card\\'><div style=\\'font-size:13px;font-weight:600;margin-bottom:3px\\'>'+p.name+'</div><div style=\\'font-size:12px;color:#6B7280;margin-bottom:5px\\'>'+p.change+'</div><div style=\\'font-size:12px;color:#0A7C6E\\'>'+p.significance+'</div></div>').join(''):'');")
lines.append("  }else if(tab==='outreach'){")
lines.append("    c.innerHTML='<div style=\\'padding:20px;color:#9CA3AF;font-size:13px\\'>Loading digest...</div>';")
lines.append("    fetch('/api/digest').then(r=>r.json()).then(d=>{")
lines.append("      if(d.message){c.innerHTML=emp('No weekly digest yet','npm run digest:weekly');return;}")
lines.append("      const p=(d.priority_accounts||[]).find(x=>x.account_name?.toLowerCase().includes(a.name.toLowerCase()));")
lines.append("      const q=(d.quick_touches||[]).find(x=>x.account_name?.toLowerCase().includes(a.name.toLowerCase()));")
lines.append("      const nf=(d.new_filings_alert||[]).find(x=>x.account_name?.toLowerCase().includes(a.name.toLowerCase()));")
lines.append("      const pw=(d.personnel_watch||[]).find(x=>x.account_name?.toLowerCase().includes(a.name.toLowerCase()));")
lines.append("      c.innerHTML=")
lines.append("        (d.week_summary?'<div class=\\'intel\\'><div class=\\'il\\'>This week</div><div class=\\'it\\'>'+d.week_summary+'</div></div>':'')+")
lines.append("        (nf?'<div class=\\'card\\' style=\\'border-left:3px solid #991B1B;margin-bottom:12px\\'><div style=\\'font-size:11px;font-weight:700;color:#991B1B;text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px\\'>New Filing Alert</div><div style=\\'font-size:13px;font-weight:600;margin-bottom:3px\\'>'+nf.filing_type+'</div><div style=\\'font-size:12px;color:#6B7280;margin-bottom:6px\\'>'+nf.summary+'</div><div style=\\'font-size:12px;color:#B45309\\'>'+nf.suggested_action+'</div></div>':'')+")
lines.append("        (pw?'<div class=\\'card\\' style=\\'border-left:3px solid #0A7C6E;margin-bottom:12px\\'><div style=\\'font-size:11px;font-weight:700;color:#0A7C6E;text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px\\'>Personnel Watch</div><div style=\\'font-size:13px;font-weight:600;margin-bottom:3px\\'>'+pw.person+'</div><div style=\\'font-size:12px;color:#6B7280;margin-bottom:4px\\'>'+pw.change+'</div><div style=\\'font-size:12px;color:#0A7C6E\\'>Window: '+pw.window+'</div></div>':'')+")
lines.append("        (p?'<div class=\\'sl\\'>Priority outreach</div><div class=\\'card\\'><div style=\\'display:flex;align-items:center;gap:8px;margin-bottom:6px\\'><span style=\\'width:22px;height:22px;border-radius:50%;background:#0F2240;color:#fff;font-size:10px;font-weight:700;display:inline-flex;align-items:center;justify-content:center\\'>'+p.priority_rank+'</span><strong>'+p.account_name+'</strong><span class=\\'bdg '+(p.urgency==='Critical'?'br':p.urgency==='High'?'ba':'bb')+'\\'>'+(p.urgency||'')+'</span></div><p style=\\'font-size:12px;color:#6B7280;margin-bottom:8px\\'>'+p.trigger+'</p>'+(p.email?'<div style=\\'background:#F9FAFB;border:1px solid #E5E7EB;border-radius:8px;padding:10px;font-size:12px;line-height:1.7\\'><strong>Subject: '+p.email.subject+'</strong><br><br>'+p.email.body.replace(/\\n/g,'<br>')+'</div>':'')+'</div>':'<div class=\\'emp\\'>'+a.name+' is not in this week top priorities</div>')+")
lines.append("        (q?'<div class=\\'sl\\' style=\\'margin-top:12px\\'>Quick touch</div><div class=\\'card\\' style=\\'font-size:13px\\'>'+q.action+'</div>':'');")
lines.append("    });")
lines.append("  }")
lines.append("}")
lines.append("init();")
lines.append("</script>")
lines.append("</body>")
lines.append("</html>`;")
lines.append("}")

content = "\n".join(lines)

with open(path, 'w') as f:
    f.write(content)

print("Done — server.js written to " + path)
print("File size: " + str(os.path.getsize(path)) + " bytes")
print("")
print("Next steps:")
print("  pkill -f 'node src/index.js'")
print("  npm start")
print("  Open http://localhost:3000")
