// accounts.js — Master account list
// Add, remove, or edit accounts here. The tracker will pick up changes on next run.

export const ACCOUNTS = [
  { id: "align_technology",       name: "Align Technology",             industry: "Healthcare / MedTech",        location: "Tempe, AZ" },
  { id: "amd",                    name: "AMD",                           industry: "Semiconductors",               location: "Santa Clara, CA" },
  { id: "anthropic",              name: "Anthropic",                     industry: "AI / ML",                     location: "San Francisco, CA" },
  { id: "asplundh",               name: "Asplundh",                      industry: "Utility services",             location: "Willow Grove, PA" },
  { id: "avanade",                name: "Avanade",                       industry: "Technology consulting",        location: "Seattle, WA" },
  { id: "bechtel",                name: "Bechtel",                       industry: "Engineering / Construction",   location: "Reston, VA" },
  { id: "best_western",           name: "Best Western",                  industry: "Hospitality",                  location: "Phoenix, AZ" },
  { id: "boyd_gaming",            name: "Boyd Gaming",                   industry: "Gaming / Hospitality",         location: "Las Vegas, NV" },
  { id: "cargill",                name: "Cargill",                       industry: "Agriculture / Commodities",    location: "Wayzata, MN" },
  { id: "cerebras",               name: "Cerebras",                      industry: "AI / ML",                     location: "Sunnyvale, CA" },
  { id: "chime",                  name: "Chime",                         industry: "Fintech",                     location: "San Francisco, CA" },
  { id: "cohere",                 name: "Cohere",                        industry: "AI / ML",                     location: "Toronto, Canada" },
  { id: "coupa",                  name: "Coupa",                         industry: "Enterprise software",          location: "San Mateo, CA" },
  { id: "databricks",             name: "Databricks",                    industry: "AI / Data",                   location: "San Francisco, CA" },
  { id: "deckers_brands",         name: "Deckers Brands",                industry: "Retail / Consumer goods",      location: "Goleta, CA" },
  { id: "deepmind_north_america", name: "DeepMind North America",        industry: "AI / ML",                     location: "New York, NY" },
  { id: "electronic_arts",        name: "Electronic Arts",               industry: "Entertainment / Gaming",       location: "Redwood City, CA" },
  { id: "flexport",               name: "Flexport",                      industry: "Logistics / Supply chain",     location: "San Francisco, CA" },
  { id: "fluor_corporation",      name: "Fluor Corporation",             industry: "Engineering / Construction",   location: "Irving, TX" },
  { id: "freeport_mcmoran",       name: "Freeport-McMoRan",              industry: "Mining / Natural resources",   location: "Phoenix, AZ" },
  { id: "godaddy",                name: "GoDaddy",                       industry: "Technology",                  location: "Tempe, AZ" },
  { id: "groq",                   name: "Groq",                          industry: "AI / ML",                     location: "Mountain View, CA" },
  { id: "hashicorp",              name: "HashiCorp",                     industry: "Enterprise software",          location: "San Francisco, CA" },
  { id: "hb_fuller",              name: "H.B. Fuller",                   industry: "Specialty chemicals",          location: "Saint Paul, MN" },
  { id: "inmar_intelligence",     name: "Inmar Intelligence",            industry: "Analytics / Technology",       location: "Winston-Salem, NC" },
  { id: "instacart",              name: "Instacart",                     industry: "E-commerce / Delivery",        location: "San Francisco, CA" },
  { id: "intellectual_ventures",  name: "Intellectual Ventures",         industry: "IP / Patent",                 location: "Bellevue, WA" },
  { id: "intuit",                 name: "Intuit",                        industry: "Financial software",           location: "Mountain View, CA" },
  { id: "johns_manville",         name: "Johns Manville",                industry: "Manufacturing",                location: "Denver, CO" },
  { id: "lambda_labs",            name: "Lambda Labs",                   industry: "AI / ML",                     location: "San Francisco, CA" },
  { id: "las_vegas_sands",        name: "Las Vegas Sands",               industry: "Gaming / Hospitality",         location: "Las Vegas, NV" },
  { id: "madrona_venture_group",  name: "Madrona Venture Group",         industry: "Venture capital",              location: "Seattle, WA" },
  { id: "microsoft",              name: "Microsoft",                     industry: "Technology",                  location: "Redmond, WA" },
  { id: "milliman",               name: "Milliman",                      industry: "Actuarial / Consulting",       location: "Seattle, WA" },
  { id: "pac12_conference",       name: "Pac-12 Conference",             industry: "Sports / Media",               location: "San Francisco, CA" },
  { id: "palo_alto_networks",     name: "Palo Alto Networks",            industry: "Cybersecurity",                location: "Santa Clara, CA" },
  { id: "pge",                    name: "PG&E",                          industry: "Energy / Utilities",           location: "Oakland, CA" },
  { id: "reddit",                 name: "Reddit",                        industry: "Technology / Social media",    location: "San Francisco, CA" },
  { id: "roblox",                 name: "Roblox Corporation",            industry: "Entertainment / Gaming",       location: "San Mateo, CA" },
  { id: "sambanova_systems",      name: "SambaNova Systems",             industry: "AI / ML",                     location: "Palo Alto, CA" },
  { id: "snap",                   name: "Snap Inc.",                     industry: "Technology / Social media",    location: "Santa Monica, CA" },
  { id: "snowflake",              name: "Snowflake",                     industry: "Enterprise software / Data",   location: "Bozeman, MT" },
  { id: "sony_north_america",     name: "Sony (North America)",          industry: "Entertainment / Technology",   location: "San Diego, CA" },
  { id: "sce",                    name: "Southern California Edison",    industry: "Energy / Utilities",           location: "Rosemead, CA" },
  { id: "spacex",                 name: "SpaceX",                        industry: "Aerospace",                   location: "Hawthorne, CA" },
  { id: "standard_ai",            name: "Standard AI",                   industry: "AI / Retail tech",            location: "San Francisco, CA" },
  { id: "starbucks",              name: "Starbucks",                     industry: "Retail / Food & Beverage",     location: "Seattle, WA" },
  { id: "stripe",                 name: "Stripe",                        industry: "Fintech",                     location: "San Francisco, CA" },
  { id: "take_two_interactive",   name: "Take-Two Interactive",          industry: "Entertainment / Gaming",       location: "New York, NY" },
  { id: "terrapower",             name: "TerraPower",                    industry: "Energy / Nuclear",             location: "Bellevue, WA" },
  { id: "tunecore",               name: "TuneCore",                      industry: "Music / Entertainment",        location: "New York, NY" },
  { id: "uber",                   name: "Uber",                          industry: "Technology / Transportation",  location: "San Francisco, CA" },
  { id: "unisys",                 name: "Unisys",                        industry: "IT services",                 location: "Blue Bell, PA" },
  { id: "unit_42",                name: "Unit 42 (Palo Alto Networks)",  industry: "Cybersecurity",                location: "Santa Clara, CA" },
  { id: "valve_corporation",      name: "Valve Corporation",             industry: "Entertainment / Gaming",       location: "Bellevue, WA" },
  { id: "wipro",                  name: "Wipro",                         industry: "IT services",                 location: "East Brunswick, NJ" },
  { id: "workday",                name: "Workday",                       industry: "Enterprise software",          location: "Pleasanton, CA" },
  { id: "xai",                    name: "xAI",                           industry: "AI / ML",                     location: "San Francisco, CA" },
  { id: "yelp",                   name: "Yelp",                          industry: "Technology",                  location: "San Francisco, CA" },
  { id: "zt_systems",             name: "ZT Systems",                    industry: "Technology / Infrastructure",  location: "Secaucus, NJ" },
  { id: "costco",                 name: "Costco",                        industry: "Retail",                      location: "Issaquah, WA" },
  { id: "coupang",                name: "Coupang",                       industry: "E-commerce",                  location: "Seattle, WA" },
  { id: "meta",                   name: "Meta",                          industry: "Technology / Social media",    location: "Menlo Park, CA" },
];
