// accounts.js — Master account list
// Add, remove, or edit accounts here. The tracker will pick up changes on next run.

export const ACCOUNTS = [
  { id: "amd",                    name: "AMD",                           industry: "Semiconductors",               location: "Santa Clara, CA" },
  { id: "anthropic",              name: "Anthropic",                     industry: "AI / ML",                     location: "San Francisco, CA" },
  { id: "asplundh",               name: "Asplundh",                      industry: "Utility services",             location: "Willow Grove, PA" },
  { id: "bechtel",                name: "Bechtel",                       industry: "Engineering / Construction",   location: "Reston, VA" },
  { id: "chime",                  name: "Chime",                         industry: "Fintech",                     location: "San Francisco, CA" },
  { id: "coupa",                  name: "Coupa",                         industry: "Enterprise software",          location: "San Mateo, CA" },
  { id: "databricks",             name: "Databricks",                    industry: "AI / Data",                   location: "San Francisco, CA" },
  { id: "electronic_arts",        name: "Electronic Arts",               industry: "Entertainment / Gaming",       location: "Redwood City, CA" },
  { id: "godaddy",                name: "GoDaddy",                       industry: "Technology",                  location: "Tempe, AZ" },
  { id: "hb_fuller",              name: "H.B. Fuller",                   industry: "Specialty chemicals",          location: "Saint Paul, MN" },
  { id: "instacart",              name: "Instacart",                     industry: "E-commerce / Delivery",        location: "San Francisco, CA" },
  { id: "johns_manville",         name: "Johns Manville",                industry: "Manufacturing",                location: "Denver, CO" },
  { id: "microsoft",              name: "Microsoft",                     industry: "Technology",                  location: "Redmond, WA" },
  { id: "milliman",               name: "Milliman",                      industry: "Actuarial / Consulting",       location: "Seattle, WA" },
  { id: "palo_alto_networks",     name: "Palo Alto Networks",            industry: "Cybersecurity",                location: "Santa Clara, CA" },
  { id: "pge",                    name: "PG&E",                          industry: "Energy / Utilities",           location: "Oakland, CA" },
  { id: "reddit",                 name: "Reddit",                        industry: "Technology / Social media",    location: "San Francisco, CA" },
  { id: "roblox",                 name: "Roblox Corporation",            industry: "Entertainment / Gaming",       location: "San Mateo, CA" },
  { id: "snowflake",              name: "Snowflake",                     industry: "Enterprise software / Data",   location: "Bozeman, MT" },
  { id: "sce",                    name: "Southern California Edison",    industry: "Energy / Utilities",           location: "Rosemead, CA" },
  { id: "spacex",                 name: "SpaceX",                        industry: "Aerospace",                   location: "Hawthorne, CA" },
  { id: "starbucks",              name: "Starbucks",                     industry: "Retail / Food & Beverage",     location: "Seattle, WA" },
  { id: "stripe",                 name: "Stripe",                        industry: "Fintech",                     location: "San Francisco, CA" },
  { id: "uber",                   name: "Uber",                          industry: "Technology / Transportation",  location: "San Francisco, CA" },
  { id: "unisys",                 name: "Unisys",                        industry: "IT services",                 location: "Blue Bell, PA" },
  { id: "unit_42",                name: "Unit 42 (Palo Alto Networks)",  industry: "Cybersecurity",                location: "Santa Clara, CA" },
  { id: "valve_corporation",      name: "Valve Corporation",             industry: "Entertainment / Gaming",       location: "Bellevue, WA" },
  { id: "workday",                name: "Workday",                       industry: "Enterprise software",          location: "Pleasanton, CA" },
  { id: "xai",                    name: "xAI",                           industry: "AI / ML",                     location: "San Francisco, CA" },
  { id: "yelp",                   name: "Yelp",                          industry: "Technology",                  location: "San Francisco, CA" },
  { id: "costco",                 name: "Costco",                        industry: "Retail",                      location: "Issaquah, WA" },
  { id: "coupang",                name: "Coupang",                       industry: "E-commerce",                  location: "Seattle, WA" },
  { id: "apple", name: "Apple", industry: "Technology", location: "Cupertina, CA" },
  { id: "polymatket", name: "Polymatket", industry: "Technology", location: "New York, NY" },
  { id: "kalshi", name: "Kalshi", industry: "Technology", location: "New York, NY" },
];
