// accounts.js — Master account list
// Add, remove, or edit accounts here. The tracker will pick up changes on next run.
// priority: true  => daily research + daily email. Others => weekly digest only.

export const ACCOUNTS = [
  { id: "amd",                name: "AMD",                        industry: "Semiconductors",              location: "Santa Clara, CA",   priority: true },
  { id: "anthropic",          name: "Anthropic",                  industry: "AI / ML",                     location: "San Francisco, CA", priority: true },
  { id: "asplundh",           name: "Asplundh",                   industry: "Utility services",            location: "Willow Grove, PA" },
  { id: "bechtel",            name: "Bechtel",                    industry: "Engineering / Construction",  location: "Reston, VA" },
  { id: "chime",              name: "Chime",                      industry: "Fintech",                     location: "San Francisco, CA" },
  { id: "coupa",              name: "Coupa",                      industry: "Enterprise software",         location: "San Mateo, CA" },
  { id: "databricks",         name: "Databricks",                 industry: "AI / Data",                   location: "San Francisco, CA", priority: true },
  { id: "electronic_arts",    name: "Electronic Arts",            industry: "Entertainment / Gaming",      location: "Redwood City, CA" },
  { id: "godaddy",            name: "GoDaddy",                    industry: "Technology",                  location: "Tempe, AZ" },
  { id: "hb_fuller",          name: "H.B. Fuller",                industry: "Specialty chemicals",         location: "Saint Paul, MN" },
  { id: "instacart",          name: "Instacart",                  industry: "E-commerce / Delivery",       location: "San Francisco, CA" },
  { id: "microsoft",          name: "Microsoft",                  industry: "Technology",                  location: "Redmond, WA",       priority: true },
  { id: "pge",                name: "PG&E",                       industry: "Energy / Utilities",          location: "Oakland, CA" },
  { id: "reddit",             name: "Reddit",                     industry: "Technology / Social media",   location: "San Francisco, CA" },
  { id: "roblox",             name: "Roblox Corporation",         industry: "Entertainment / Gaming",      location: "San Mateo, CA" },
  { id: "snowflake",          name: "Snowflake",                  industry: "Enterprise software / Data",  location: "Bozeman, MT",       priority: true },
  { id: "sce",                name: "Southern California Edison", industry: "Energy / Utilities",          location: "Rosemead, CA" },
  { id: "spacex",             name: "SpaceX",                     industry: "Aerospace",                   location: "Hawthorne, CA",     priority: true },
  { id: "starbucks",          name: "Starbucks",                  industry: "Retail / Food & Beverage",    location: "Seattle, WA" },
  { id: "stripe",             name: "Stripe",                     industry: "Fintech",                     location: "San Francisco, CA", priority: true },
  { id: "uber",               name: "Uber",                       industry: "Technology / Transportation", location: "San Francisco, CA", priority: true },
  { id: "unisys",             name: "Unisys",                     industry: "IT services",                 location: "Blue Bell, PA" },
  { id: "unit_42",            name: "Unit 42 (Palo Alto Networks)", industry: "Cybersecurity",             location: "Santa Clara, CA" },
  { id: "valve_corporation",  name: "Valve Corporation",          industry: "Entertainment / Gaming",      location: "Bellevue, WA" },
  { id: "workday",            name: "Workday",                    industry: "Enterprise software",         location: "Pleasanton, CA",    priority: true },
  { id: "xai",                name: "xAI",                        industry: "AI / ML",                     location: "San Francisco, CA", priority: true },
  { id: "yelp",               name: "Yelp",                       industry: "Technology",                  location: "San Francisco, CA" },
  { id: "costco",             name: "Costco",                     industry: "Retail",                      location: "Issaquah, WA" },
  { id: "coupang",            name: "Coupang",                    industry: "E-commerce",                  location: "Seattle, WA" },
  { id: "apple",              name: "Apple",                      industry: "Technology",                  location: "Cupertino, CA",     priority: true },
  { id: "polymarket",         name: "Polymarket",                 industry: "Technology",                  location: "New York, NY" },
  { id: "kalshi",             name: "Kalshi",                     industry: "Technology",                  location: "New York, NY" },
  { id: "anduril",            name: "Anduril Industries",         industry: "Defense technology",          location: "Costa Mesa, CA",    priority: true },
  { id: "cargill",            name: "Cargill",                    industry: "Agriculture / Food",          location: "Minnetonka, MN" },
  { id: "terrapower",         name: "TerraPower",                 industry: "Nuclear energy",              location: "Bellevue, WA" },
  { id: "meta",               name: "Meta",                       industry: "Technology / Social media",   location: "Menlo Park, CA",    priority: true },
  { id: "scale_ai",           name: "Scale AI",                   industry: "AI / ML",                     location: "San Francisco, CA", priority: true },
  { id: "figma",              name: "Figma",                      industry: "Design software",             location: "San Francisco, CA" },
  { id: "cloudflare",         name: "Cloudflare",                 industry: "Cloud / Security",            location: "San Francisco, CA" },
  { id: "palantir",           name: "Palantir Technologies",      industry: "Data analytics",              location: "Denver, CO",        priority: true },
  { id: "ramp",               name: "Ramp",                       industry: "Fintech",                     location: "New York, NY" },
  { id: "brex",               name: "Brex",                       industry: "Fintech",                     location: "San Francisco, CA" },
  { id: "rippling",           name: "Rippling",                   industry: "HR / Enterprise software",    location: "San Francisco, CA" },
  { id: "deel",               name: "Deel",                       industry: "HR / Payroll",                location: "San Francisco, CA" },
  { id: "canva",              name: "Canva",                      industry: "Design software",             location: "Sydney, AU" },
  { id: "notion",             name: "Notion",                     industry: "Productivity software",       location: "San Francisco, CA" },
];
