#!/usr/bin/env node
// setup.js — Interactive first-run setup wizard
// Creates your .env file with guided prompts

import { createInterface } from 'readline';
import { writeFileSync, existsSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const ENV_PATH = join(ROOT, '.env');

const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = (q, def = '') => new Promise(res => {
  rl.question(def ? `${q} (default: ${def}): ` : `${q}: `, ans => res(ans.trim() || def));
});

console.log('\n╔══════════════════════════════════════════╗');
console.log('║   Legal Account Tracker — Setup Wizard  ║');
console.log('╚══════════════════════════════════════════╝\n');

if (existsSync(ENV_PATH)) {
  const overwrite = await ask('.env already exists. Overwrite? (y/N)', 'N');
  if (overwrite.toLowerCase() !== 'y') {
    console.log('Setup cancelled. Edit .env manually.');
    process.exit(0);
  }
}

console.log('\n── Step 1: Anthropic API ──');
console.log('Get your API key at https://console.anthropic.com\n');
const apiKey = await ask('Anthropic API key (sk-ant-...)');

console.log('\n── Step 2: Email (Outlook / Office 365) ──');
console.log('Use an app password — generate at https://account.microsoft.com/security\n');
const emailUser = await ask('Your Outlook email address');
const emailPass = await ask('App password (NOT your regular password)');
const emailTo   = await ask('Send notifications to (press Enter for same address)', emailUser);

console.log('\n── Step 3: Microsoft Teams webhook (optional) ──');
console.log('In Teams: channel → ··· → Connectors → Incoming Webhook\n');
const teamsUrl = await ask('Teams webhook URL (press Enter to skip)', '');

console.log('\n── Step 4: Salesforce (optional) ──');
const sfEnabled = await ask('Enable Salesforce sync? (y/N)', 'N');
let sfVars = '';
if (sfEnabled.toLowerCase() === 'y') {
  const sfUser = await ask('Salesforce username');
  const sfPass = await ask('Salesforce password');
  const sfToken = await ask('Salesforce security token');
  const sfClientId = await ask('Connected App client ID');
  const sfClientSecret = await ask('Connected App client secret');
  sfVars = `\nSF_LOGIN_URL=https://login.salesforce.com\nSF_CLIENT_ID=${sfClientId}\nSF_CLIENT_SECRET=${sfClientSecret}\nSF_USERNAME=${sfUser}\nSF_PASSWORD=${sfPass}\nSF_SECURITY_TOKEN=${sfToken}`;
}

console.log('\n── Step 5: Schedule ──');
const researchCron = await ask('Daily research time (cron, default = 7 AM)', '0 7 * * *');
const digestCron   = await ask('Weekly digest time (cron, default = Mon 8 AM)', '0 8 * * 1');

const env = `# Legal Account Tracker — generated by setup wizard
# ${new Date().toISOString()}

ANTHROPIC_API_KEY=${apiKey}

EMAIL_HOST=smtp.office365.com
EMAIL_PORT=587
EMAIL_USER=${emailUser}
EMAIL_PASS=${emailPass}
EMAIL_FROM=${emailUser}
EMAIL_TO=${emailTo}
${teamsUrl ? `\nTEAMS_WEBHOOK_URL=${teamsUrl}` : ''}
${sfVars}

RESEARCH_CRON=${researchCron}
DIGEST_CRON=${digestCron}
RESEARCH_CONCURRENCY=3
RESEARCH_STALE_DAYS=1

PORT=3000
NODE_ENV=production
LOG_LEVEL=info
`;

writeFileSync(ENV_PATH, env);
console.log('\n✓ .env created at', ENV_PATH);
console.log('\nNext steps:');
console.log('  1. npm install');
console.log('  2. npm run research:all    ← kick off first research run');
console.log('  3. npm start               ← start scheduler + dashboard');
console.log('\nDashboard will be at: http://localhost:3000\n');

rl.close();
